"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.rethrowDecorator = exports.isError = void 0;
function isError(e) {
    const exception = e;
    return !!exception.name && !!exception.message;
}
exports.isError = isError;
function rethrowDecorator(func, beforeRethrow) {
    const f = (...args) => __awaiter(this, void 0, void 0, function* () {
        try {
            return yield func(...args);
        }
        catch (e) {
            yield beforeRethrow(e, ...args);
            throw e;
        }
    });
    return f;
}
exports.rethrowDecorator = rethrowDecorator;
//# sourceMappingURL=exceptions.js.map